### ISSUE TITLE
[BUG] error creating readme when using loops in variables

### ISSUE THREAD

**Issue by TheGrussalo** [christosgalano/bicep-docs#35]
When attempting to create a readme for a module the error message `error processing main.bicep: error parsing Bicep variables` is returned.
The modules uses Types and loops in the variables which may be the cause.

## Description
When running the command:
```pwsh
bicep-docs.exe -V --input . --output README.md
```
The error is returned:
```
error processing main.bicep: error parsing Bicep variables
```

## Steps to Reproduce
- Create a `main.go` file with the following contents:
```bicep
type ipAction = 'Allow' | 'Deny'

@description('Define an array of IP objects')
type ipDefinition = {
  @minLength(7)
  @maxLength(18)
  ip: string

  @maxLength(32)
  name: string  

  @minLength(6)
  @maxLength(32)
  description: string  

  action: ipAction

  @minValue(1000)
  @maxValue(50000)
  priority: int
  
  tag: string?

  port: int?
}[]


@description('First Array of IP Definitions. Required')
param ipDefinitionArray1 ipDefinition

@description('Second Array of IP Definitions. Optional')
param ipDefinitionArray2 ipDefinition = []

var allIps = union(ipDefinitionArray1,ipDefinitionArray2)

@description('Appends /32 if the IP is not specified as CIDR')
var allIpsCidrFormatted = [
  for this in allIps : {
    ip : contains(this.ip,'/') ? this.ip : '${this.ip}/32'
    name: this.name  
    action: this.action
    priority: this.action
    description: this.description
    tag: this.?tag ?? null
    port: this.?port ?? null
  }
]

@description('Output IP array in the format for Azure Storage Accounts')
var ipFormatWithDuplicates = [
  for this in allIpsCidrFormatted : {
    value: this.ip
    action: this.action
  }
]

@description('Pass through the full unioned ipDefinition object')
output ipFormatAllFields array = allIpsCidrFormatted

output cidrs array = allIpsCidrFormatted
output ips array = ipFormatWithDuplicates
output allIps array = allIps

```
- Run the command to generate the file:
```pwsh
bicep-docs.exe -V --input . --output README.md
```

From commenting the code I believe the variable that it is having problems with is:
```bicep
var ipFormatWithDuplicates = [
  for this in allIpsCidrFormatted : {
    value: this.ip
    action: this.action
  }
]
```

## Context
I'm trying to use the tool to iterate through some in-house custom modules and there are a couple of failures.
This is one of our older modules which may be re-written but thought it was worth raising a bug.

## Your Environment
- Version used: bicep-docs version v1.2.0
- Operating System and version: Windows 11 23H2

**Comment by christosgalano** [comment]
Thank you @TheGrussalo for reporting this issue. The new version v1.2.1 addresses exactly that.

Previously, bicep-docs would fail with "error parsing Bicep variables" when processing Bicep templates containing array comprehension variables that reference other array variables (like `ipFormatWithDuplicates` referencing `allIpsCidrFormatted`).

The parser now correctly handles multiple array transformations in sequence and their corresponding ARM template copy operations.

You can upgrade using `brew upgrade bicep-docs`, `go install github.com/christosgalano/bicep-docs/cmd/bicep-docs@v1.2.1`, or by downloading the latest binary from the releases page.
