### ISSUE TITLE
document variables in main.bicep

### ISSUE THREAD

**Issue by winticloud** [christosgalano/bicep-docs#5]
## Detailed Description
It would be wonderful to have bicep-docs document variables as well as usually variables will be used in main.bicep

## Context
example of a Bicep variable
```bicep
var stringVar = 'example value'
```

## Possible Implementation
same way as for parameters

**Comment by christosgalano** [comment]
Thanks for your feedback. Release v1.1.0 is out and includes vars and user-defined data types & functions.

I am closing this issue.
