### ISSUE TITLE
document user-defined data types in main.bicep

### ISSUE THREAD

**Issue by winticloud** [christosgalano/bicep-docs#6]
## Detailed Description
It would be wonderful to have bicep-docs document user-defined data types as well in main.bicep

## Context
example of a Bicep user-defined data types 
```bicep
// Bicep data type reference
type myStringType = string

// user-defined type reference
type myOtherStringType = myStringType
```

## Possible Implementation
same way as for parameters

**Comment by christosgalano** [comment]
Thanks for your feedback. Release v1.1.0 is out and includes vars and user-defined data types & functions.

I am closing this issue.
