### ISSUE TITLE
document user-defined functions (still in preview) in main.bicep

### ISSUE THREAD

**Issue by winticloud** [christosgalano/bicep-docs#7]
## Detailed Description
It would be wonderful to have bicep-docs document User-defined functions as well in main.bicep.

## Context
Although this is still a preview feature, it would be nice to be ready to document it, once they turn GA.

example of a Bicep User-defined functions
```bicep
func sayHelloObject(name string) object => {
  hello: 'Hi ${name}!'
}
```

To enable this preview, modify your project's bicepconfig.json file to include the following JSON:
```bicep
{
  "experimentalFeaturesEnabled": {
    "userDefinedFunctions": true
  }
}
```

## Possible Implementation
same way as for parameters

**Comment by christosgalano** [comment]
Thanks for your feedback. Release v1.1.0 is out and includes vars and user-defined data types & functions.

I am closing this issue.
