### ISSUE TITLE
multiline markup description text not correctly parsed

### ISSUE THREAD

**Issue by winticloud** [christosgalano/bicep-docs#8]
## Description
bicep-docs is parsing multiline markup description text not correctly 
As described in the [MS Learn article](https://learn.microsoft.com/en-gb/azure/azure-resource-manager/bicep/parameters) it is allowed to have multiline markup language text for example for description text of parameters. 

```bicep
@description('''
Storage account name restrictions:
- Storage account names must be between 3 and 24 characters in length and may contain numbers and lowercase letters only.
- Your storage account name must be unique within Azure. No two storage accounts can have the same name.
''')
@minLength(3)
@maxLength(24)
param storageAccountName string
```

## Parameters

| Name | Type | Description | Default |
| --- | --- | --- | --- |
| storageAccountName | string | Storage account name restrictions: <ul><li>Storage account names must be between 3 and 24 characters in length and may contain numbers and lowercase letters only.</li><li>Your storage account name must be unique within Azure. No two storage accounts can have the same name.</li></ul> |

## Actual Behavior
| Name | Type | Description | Default |
| --- | --- | --- | --- |
| storageAccountName | string | Storage account name restrictions:
- Storage account names must be between 3 and 24 characters in length and may contain numbers and lowercase letters only.
- Your storage account name must be unique within Azure. No two storage accounts can have the same name.
 |  |
## Possible Fix
The problem might be solved by using a combination of markup language and HTML elements. In the case of a list the following HTML elements `<ul><li>First</li><li>Second</li></ul>` seem to solve the problem.
Here's a link to some examples [Table example](https://bobbyhadz.com/blog/markdown-write-lists-inside-table)

## Steps to Reproduce

use the following bicep code
```bicep
@description('''
Storage account name restrictions:
- Storage account names must be between 3 and 24 characters in length and may contain numbers and lowercase letters only.
- Your storage account name must be unique within Azure. No two storage accounts can have the same name.
''')
@minLength(3)
@maxLength(24)
param storageAccountName string
```

## Your Environment
same environment as for issues [4](https://github.com/christosgalano/bicep-docs/issues/4)

**Comment by christosgalano** [comment]
Thanks for your feedback @winticloud. Version v1.1.1 solves this issue. It now allows newline characters by replacing '\n' with '<br>'. 

One important note is that your list won't show bullets but '-', since the description is just a Markdown table column.

I am closing this issue, keep providing feedback to make **bicep-docs** even better.

**Comment by winticloud** [comment]
@christosgalano to me the issue doesn't seem to be solved. I can see you're using `<br>` but the text doesn't seem to stay in the table cell. See below:
**Screenshot:**
![image](https://github.com/christosgalano/bicep-docs/assets/11757681/0623487b-589a-4211-9843-37a93dd6fd64)
**Codeview:**
```markup
| Name | Type | Description | Default |
| --- | --- | --- | --- |
| storageAccountName | string | Storage account name restrictions:
<br>- Storage account names must be between 3 and 24 characters in length and may contain numbers and lowercase letters only.
<br>- Your storage account name must be unique within Azure. No two storage accounts can have the same name.
<br> |  |
```
**screenshot of code:**
![image](https://github.com/christosgalano/bicep-docs/assets/11757681/5ddbbde1-d46b-4c9e-a528-811105a88327)

would you be so kind and have another look?

**Comment by christosgalano** [comment]
You are right @winticloud, the issue was that on Windows new lines are '\r\n', so they replace all did not actually replace the '\r'.

Since it is still early in the creation of this tool, I will pack all the improvements and fixes and I am going to relaunch the v1.0.0 version ... I am doing some final modifications and then I am going to publish it ... I would your feedback once more.

I will close this issue, once the v1.0.0 is published and you confirm that everything works smoothly.

**Comment by winticloud** [comment]
I'm happy to test again and give feedback.

**Comment by christosgalano** [comment]
@winticloud v1.0.0 is out. So, try it out and let me know if everything works as expected. I also added cross-platform tests to validate that the program's behavior is as expected.

**Comment by winticloud** [comment]
looks much better this time, see screenshot:
![image](https://github.com/christosgalano/bicep-docs/assets/11757681/9b84bbb2-155e-4efe-b036-249bab95534c)
**screenshot of code:**
![image](https://github.com/christosgalano/bicep-docs/assets/11757681/ad53e1d7-53b2-4e59-8bf2-8fe208a05a6b)
thank you very much

**Comment by christosgalano** [comment]
Great! I am closing this issue.
