### ISSUE TITLE
Variables markup table should have a description column

### ISSUE THREAD

**Issue by winticloud** [christosgalano/bicep-docs#9]
## Detailed Description
bicep-docs version 1.0.1 has support to document variables, that's great! 
It looks like this:
| Name |
| --- |
| varRouteTableName| 

However, as we cannot have `@description('sometext')` decorators for variables and have bicep-docs read it and generate the description automatically, we need to document it manually. In the main.bicep file we can use the line comment for that purpose. 
```bicep
// build naming convention based resource names
var varFortiRgName = '${parEnvironment}${parCustomerPrefix}-fw1-${parLocationPostfix}-rg'
```
If we want to document it using bicep-docs, we have to add the description text manually, 

> **sidenote**: knowing, that we could loose the manually added description, when running bicep-docs again

 To add the description manually, it'd be very useful, if an empty markup table column with header **description** was added to the table. As of version 1.0.1 the variable markup table so far only holds the variables name.

## Possible Implementation

| Name |Description
| --- |--- |
| varRouteTableName| enter description nmanually|

## Your Environment

same environment as for issues [4](https://github.com/christosgalano/bicep-docs/issues/4)

**Comment by christosgalano** [comment]
Thanks for your suggestion @winticloud. I added the Description column with empty values until metadata is supported variables. That should make it easier to fill in manually.

I am closing this issue, keep providing feedback to make **bicep-docs** even
